/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPortalAdminRouteImport } from './routes/_authenticated/portal.admin'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports.$id'
import { Route as AuthenticatedPortalReportsIdRouteImport } from './routes/_authenticated/portal.reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAdminRoute =
  AuthenticatedPortalAdminRouteImport.update({
    id: '/portal/admin',
    path: '/portal/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalReportsIdRoute =
  AuthenticatedPortalReportsIdRouteImport.update({
    id: '/portal/reports/$id',
    path: '/portal/reports/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRoute
  '/report': typeof AuthenticatedReportRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/portal/reports/$id': typeof AuthenticatedPortalReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRoute
  '/report': typeof AuthenticatedReportRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/portal/reports/$id': typeof AuthenticatedPortalReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/staff': typeof StaffRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/portal/reports/$id': typeof AuthenticatedPortalReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/staff'
    | '/report'
    | '/portal/admin'
    | '/reports/$id'
    | '/portal/'
    | '/reports/'
    | '/portal/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/staff'
    | '/report'
    | '/portal/admin'
    | '/reports/$id'
    | '/portal'
    | '/reports'
    | '/portal/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/staff'
    | '/_authenticated/report'
    | '/_authenticated/portal/admin'
    | '/_authenticated/reports/$id'
    | '/_authenticated/portal/'
    | '/_authenticated/reports/'
    | '/_authenticated/portal/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/admin': {
      id: '/_authenticated/portal/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof AuthenticatedPortalAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/reports/$id': {
      id: '/_authenticated/portal/reports/$id'
      path: '/portal/reports/$id'
      fullPath: '/portal/reports/$id'
      preLoaderRoute: typeof AuthenticatedPortalReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedPortalAdminRoute: typeof AuthenticatedPortalAdminRoute
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedPortalReportsIdRoute: typeof AuthenticatedPortalReportsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedPortalAdminRoute: AuthenticatedPortalAdminRoute,
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedPortalReportsIdRoute: AuthenticatedPortalReportsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
